sudo: required
services:
  - docker

before_install:
  - docker build -t saxenapawan800/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true saxenapawan800/docker-react-app npm run test